name: Deploy Hexo to github pages
on: 
  push:
    branches:
      - main
    paths:
      - public/**

jobs:
  deploy:
    name: Merge hexo blog with my previous blog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hexo blog
        uses: actions/checkout@v3
        with:
          repository: liuxingzhi/hexo-blog
          path: hexo-blog
      - name:
        run: echo ${{ secrets.REPO_COMMIT_TOKEN }}

      - name: Checkout main blog
        uses: actions/checkout@v3
        with:
          repository: liuxingzhi/liuxingzhi.github.io
          path: liuxingzhi.github.io
          token:  ${{ secrets.REPO_COMMIT_TOKEN }}
      
      - name: Merge hexo to main blog
        run: |
          cp -R hexo-blog/public/. liuxingzhi.github.io/genshin/
          cd liuxingzhi.github.io
          git add .
          git commit -m "Automatic publish from github.com/hexo-blog"
          git push



